export enum Currency {
    RUB = 'RUB',
    EUR = 'EUR',
    USD = 'USD',
    BYN = 'BYN',
    BTC = 'BTC',
    UAH = 'UAH',
    KZT = 'KZT',
    PLN = 'PLN',
    GBP = 'GBP',
    CNY = 'CNY',
    JPY = 'JPY',
    CAD = 'CAD',
    AED = 'AED',
}
