export enum Country {
    RU = 'Russia',
    BY = 'Belarus',
    UA = 'Ukraine',
    KZ = 'Kazakhstan',
    US = 'USA',
    PL = 'Poland',
    UK = 'United Kingdom',
    CN = 'China',
    JP = 'Japan',
    CA = 'Canada',
    AE = 'UAE',
    DE = 'Germany',
    ES = 'Spain',
    FR = 'France',
    IN = 'India',
}
